### PR TITLE
Update development dependencies

### PR DESCRIPTION
**Pull request by sirreal**
Update dependencies (testing and linting tools).

Apply `eslint --fix`.

### CODE REVIEW

**Comment by ockham** [comment]
:slightly_frowning_face: Tests are failing with

> Unexpected token ...
Referenced from: /home/travis/build/Automattic/xgettext-js/.eslintrc.json

**Comment by ockham** [comment]
And running `npm i && eslint .` locally, I get

```
Cannot find module 'eslint-config-wpcalypso'
Referenced from: /home/bernie/src/xgettext-js/.eslintrc.json
```

**Comment by aduth** [comment]
@ockham Specific to a Node version perhaps? "WFM" on my end.

**Comment by ockham** [comment]
Tried with both `8.11.1` and `6.14.2`. No dice :slightly_frowning_face:

**Comment by aduth** [comment]
@ockham Try removing the existing dependencies first via `rm -rf node_modules` ? I'm on Node v8.11.2 on my end so I wouldn't expect it to be much different. I'm also working from a fresh clone.

**Comment by aduth** [comment]
Travis seems to be having trouble as well.

Aside: When I run `npm install` on this branch, I see local changes to `package-lock.json`

**Comment by sirreal** [comment]
Travis should be fixed by #16

**Comment by ockham** [comment]
Okay, so let's see what happens after merging #16 and rebasing this.

**Comment by sirreal** [comment]
Rebased, fresh package-lock with npm@6

**Pull request merged**
